// Auto-generated from Cloudinary API — do not edit manually

// ── Lamitak: product-images/{num}.{ext} ─────────────────────────────────
// numeric ID extracted from product code (e.g. "WY 5216D" → 5216)
const PI = "https://res.cloudinary.com/varindo/image/upload/product-images";

export const LAMITAK_NUM_FMT: Record<string, string> = {
  "1009": "webp",
  "1010": "webp",
  "1011": "webp",
  "1012": "jpg",
  "1018": "webp",
  "1019": "webp",
  "1021": "webp",
  "1022": "jpg",
  "1023": "webp",
  "1029": "webp",
  "1032": "webp",
  "1066": "webp",
  "1091": "webp",
  "1103": "webp",
  "1104": "webp",
  "1108": "webp",
  "1109": "webp",
  "1111": "webp",
  "1112": "webp",
  "1113": "webp",
  "1119": "webp",
  "1120": "webp",
  "1121": "webp",
  "1124": "webp",
  "1125": "webp",
  "1126": "webp",
  "1130": "webp",
  "1132": "webp",
  "1133": "webp",
  "1134": "webp",
  "1135": "webp",
  "1136": "webp",
  "1137": "webp",
  "1138": "webp",
  "1139": "webp",
  "1140": "webp",
  "1141": "webp",
  "1143": "webp",
  "1144": "webp",
  "1145": "webp",
  "1146": "webp",
  "1147": "webp",
  "1149": "webp",
  "1150": "webp",
  "1151": "webp",
  "1152": "webp",
  "1153": "webp",
  "1154": "webp",
  "1155": "webp",
  "1156": "webp",
  "1157": "webp",
  "1158": "webp",
  "1159": "webp",
  "1161": "webp",
  "1162": "webp",
  "1163": "webp",
  "1165": "webp",
  "1166": "webp",
  "1167": "webp",
  "1168": "webp",
  "1169": "webp",
  "1170": "webp",
  "1171": "webp",
  "1172": "webp",
  "1173": "webp",
  "1175": "webp",
  "1176": "webp",
  "1178": "webp",
  "1179": "webp",
  "1180": "webp",
  "1181": "webp",
  "1188": "webp",
  "1205": "jpg",
  "1206": "jpg",
  "1207": "webp",
  "1208": "jpg",
  "1239": "jpg",
  "1240": "webp",
  "1241": "webp",
  "1244": "webp",
  "1245": "webp",
  "1246": "webp",
  "1247": "webp",
  "1248": "webp",
  "1249": "webp",
  "1257": "webp",
  "1258": "webp",
  "1259": "webp",
  "1260": "webp",
  "1261": "webp",
  "1262": "webp",
  "1263": "webp",
  "1264": "webp",
  "1265": "webp",
  "1266": "webp",
  "1267": "webp",
  "1268": "webp",
  "1269": "webp",
  "1270": "webp",
  "1271": "webp",
  "1272": "webp",
  "1273": "webp",
  "1274": "webp",
  "1275": "webp",
  "1276": "webp",
  "1277": "webp",
  "1278": "webp",
  "1279": "webp",
  "1280": "webp",
  "1281": "webp",
  "1282": "webp",
  "1283": "webp",
  "1284": "webp",
  "1285": "jpg",
  "1286": "webp",
  "1287": "jpg",
  "1288": "webp",
  "1289": "jpg",
  "1329": "webp",
  "1331": "webp",
  "1333": "jpg",
  "1334": "jpg",
  "1335": "jpg",
  "1336": "webp",
  "1337": "webp",
  "1338": "jpg",
  "1341": "jpg",
  "1342": "jpg",
  "1343": "jpg",
  "1349": "jpg",
  "1350": "jpg",
  "1351": "jpg",
  "1352": "webp",
  "1353": "jpg",
  "1354": "webp",
  "1355": "webp",
  "1358": "webp",
  "1360": "jpg",
  "1361": "jpg",
  "1362": "jpg",
  "1363": "jpg",
  "1364": "webp",
  "1365": "webp",
  "1366": "jpg",
  "1368": "jpg",
  "1369": "webp",
  "1370": "jpg",
  "1371": "webp",
  "1372": "jpg",
  "1373": "jpg",
  "1374": "jpg",
  "1375": "webp",
  "1376": "webp",
  "1377": "jpg",
  "1378": "jpg",
  "1379": "jpg",
  "1380": "jpg",
  "1381": "jpg",
  "1382": "jpg",
  "1383": "jpg",
  "1384": "jpg",
  "1385": "jpg",
  "1386": "webp",
  "1387": "jpg",
  "1388": "webp",
  "1389": "jpg",
  "1390": "webp",
  "1391": "webp",
  "1392": "webp",
  "1393": "jpg",
  "1402": "jpg",
  "1403": "webp",
  "1404": "webp",
  "4209": "webp",
  "4210": "webp",
  "4211": "webp",
  "4217": "jpg",
  "4218": "webp",
  "4219": "webp",
  "4220": "jpg",
  "4221": "jpg",
  "4222": "webp",
  "4223": "webp",
  "4224": "webp",
  "4225": "jpg",
  "4229": "jpg",
  "4230": "webp",
  "4231": "webp",
  "4232": "webp",
  "4236": "webp",
  "4237": "webp",
  "4238": "webp",
  "4239": "webp",
  "4240": "webp",
  "4242": "jpg",
  "4243": "webp",
  "4244": "webp",
  "4245": "webp",
  "4246": "jpg",
  "4247": "jpg",
  "4248": "webp",
  "4249": "webp",
  "4250": "webp",
  "4251": "webp",
  "4252": "jpg",
  "4253": "webp",
  "4254": "jpg",
  "4255": "webp",
  "4256": "webp",
  "4257": "webp",
  "4258": "webp",
  "4259": "webp",
  "4260": "webp",
  "4261": "webp",
  "4262": "webp",
  "4263": "webp",
  "4264": "webp",
  "4265": "webp",
  "4266": "webp",
  "4267": "webp",
  "4268": "webp",
  "4269": "webp",
  "4270": "webp",
  "4271": "webp",
  "4272": "webp",
  "4273": "webp",
  "4274": "webp",
  "4275": "webp",
  "4276": "webp",
  "4310": "jpg",
  "4314": "jpg",
  "4316": "webp",
  "4318": "webp",
  "4319": "webp",
  "4320": "jpg",
  "4321": "jpg",
  "4322": "jpg",
  "4323": "jpg",
  "4324": "webp",
  "4325": "jpg",
  "4329": "webp",
  "4330": "webp",
  "5101": "webp",
  "5102": "webp",
  "5103": "webp",
  "5104": "webp",
  "5107": "webp",
  "5109": "webp",
  "5110": "webp",
  "5112": "webp",
  "5113": "webp",
  "5115": "webp",
  "5116": "webp",
  "5117": "webp",
  "5118": "webp",
  "5119": "webp",
  "5120": "webp",
  "5123": "webp",
  "5124": "webp",
  "5125": "webp",
  "5127": "webp",
  "5128": "webp",
  "5129": "webp",
  "5133": "webp",
  "5138": "webp",
  "5139": "webp",
  "5142": "webp",
  "5143": "webp",
  "5144": "webp",
  "5145": "webp",
  "5146": "webp",
  "5147": "webp",
  "5148": "webp",
  "5149": "webp",
  "5150": "webp",
  "5151": "webp",
  "5152": "webp",
  "5153": "webp",
  "5154": "webp",
  "5155": "webp",
  "5156": "webp",
  "5157": "webp",
  "5158": "webp",
  "5159": "webp",
  "5160": "webp",
  "5213": "webp",
  "5214": "webp",
  "5215": "webp",
  "5216": "webp",
  "5217": "webp",
  "5218": "webp",
  "5230": "webp",
  "5231": "webp",
  "5232": "webp",
  "5233": "webp",
  "5239": "webp",
  "5240": "webp",
  "5241": "webp",
  "5242": "webp",
  "5243": "webp",
  "5244": "webp",
  "5245": "webp",
  "5250": "jpg",
  "5251": "jpg",
  "5252": "webp",
  "5253": "webp",
  "5254": "webp",
  "5255": "webp",
  "5256": "webp",
  "5257": "webp",
  "5258": "webp",
  "5259": "webp",
  "5260": "webp",
  "5261": "webp",
  "5262": "jpg",
  "5263": "jpg",
  "5264": "jpg",
  "5265": "webp",
  "5266": "webp",
  "5267": "webp",
  "5268": "webp",
  "5269": "webp",
  "5270": "webp",
  "5271": "webp",
  "5272": "webp",
  "5273": "webp",
  "5274": "webp",
  "5275": "webp",
  "5276": "webp",
  "5277": "jpg",
  "5278": "webp",
  "5279": "webp",
  "5280": "webp",
  "5281": "webp",
  "5283": "webp",
  "5284": "webp",
  "5285": "webp",
  "5286": "webp",
  "5287": "webp",
  "5288": "webp",
  "5289": "webp",
  "5290": "webp",
  "5291": "webp",
  "5292": "webp",
  "5293": "webp",
  "5294": "webp",
  "5295": "webp",
  "5296": "webp",
  "5297": "webp",
  "5298": "webp",
  "5299": "jpg",
  "5308": "jpg",
  "5309": "webp",
  "5310": "webp",
  "5319": "webp",
  "5320": "webp",
  "5321": "webp",
  "5322": "webp",
  "5335": "webp",
  "5336": "webp",
  "5337": "webp",
  "5338": "webp",
  "5339": "jpg",
  "5340": "webp",
  "5342": "jpg",
  "5343": "jpg",
  "5344": "webp",
  "5345": "webp",
  "5346": "webp",
  "5353": "jpg",
  "5354": "jpg",
  "5355": "jpg",
  "5356": "jpg",
  "5357": "jpg",
  "5358": "jpg",
  "5359": "webp",
  "5601": "webp",
  "5602": "webp",
  "5603": "jpg",
  "5604": "jpg",
  "5605": "webp",
  "7201": "webp",
  "7202": "webp",
  "7203": "webp",
  "7204": "webp",
  "7205": "webp",
  "7206": "webp",
  "7207": "webp",
  "7208": "webp",
  "7209": "webp",
  "7210": "webp",
  "9310": "jpg",
  "9500": "webp",
  "9502": "webp",
  "11011": "webp",
  "11012": "jpg",
  "11029": "webp",
  "11032": "webp",
  "11103": "webp",
  "11104": "webp",
  "11108": "webp",
  "11109": "webp",
  "11112": "webp",
  "11113": "webp",
  "11120": "webp",
  "11121": "webp",
  "11124": "webp",
  "11130": "webp",
  "11132": "webp",
  "11133": "webp",
  "11134": "webp",
  "11135": "webp",
  "11136": "webp",
  "11137": "webp",
  "11138": "webp",
  "11141": "webp",
  "11143": "webp",
  "11144": "webp",
  "11147": "webp",
  "11149": "webp",
  "11150": "webp",
  "11151": "webp",
  "11152": "webp",
  "11154": "webp",
  "11155": "webp",
  "11159": "webp",
  "11162": "webp",
  "11163": "webp",
  "11165": "webp",
  "11166": "webp",
  "11167": "webp",
  "11172": "webp",
  "11176": "webp",
  "11178": "webp",
  "11179": "webp",
  "11180": "webp",
  "11188": "webp",
  "11259": "webp",
  "11260": "webp",
  "11261": "webp",
  "11262": "webp",
  "11263": "webp",
  "11264": "webp",
  "11265": "webp",
  "11266": "webp",
  "11267": "webp",
  "11268": "webp",
  "11269": "webp",
  "11270": "webp",
  "11271": "webp",
  "11272": "webp",
  "11273": "webp",
  "11274": "webp",
  "11275": "webp",
  "11276": "webp",
  "11277": "webp",
  "11278": "webp",
  "11279": "webp",
  "11280": "webp",
  "11281": "webp",
  "11282": "webp",
  "11283": "webp",
  "11284": "webp",
  "11286": "webp",
  "11287": "jpg",
  "11337": "webp",
  "11338": "jpg",
  "11353": "jpg",
  "11358": "webp",
  "11373": "jpg",
  "11374": "jpg",
  "11381": "jpg",
  "11382": "jpg",
  "11383": "jpg",
  "11386": "webp",
  "11387": "jpg",
  "11388": "webp",
  "11389": "jpg",
  "11390": "webp",
  "11391": "webp",
  "11392": "webp",
  "11393": "jpg",
  "14220": "jpg",
  "14221": "jpg",
  "14222": "webp",
  "14223": "webp",
  "14266": "webp",
  "14267": "webp",
  "14268": "webp",
  "14269": "webp",
  "15101": "webp",
  "15102": "webp",
  "15107": "webp",
  "15109": "webp",
  "15115": "webp",
  "15117": "webp",
  "15118": "webp",
  "15127": "webp",
  "15128": "webp",
  "15142": "webp",
  "15143": "webp",
  "15144": "webp",
  "15145": "webp",
  "15146": "webp",
  "15147": "webp",
  "15148": "webp",
  "15149": "webp",
  "15150": "webp",
  "15151": "webp",
  "15152": "webp",
  "15153": "webp",
  "15154": "webp",
  "15155": "webp",
  "15156": "webp",
  "15157": "webp",
  "15158": "webp",
  "15159": "webp",
  "15160": "webp",
  "15213": "webp",
  "15214": "webp",
  "15215": "webp",
  "15216": "webp",
  "15217": "webp",
  "15230": "webp",
  "15232": "webp",
  "15239": "webp",
  "15240": "webp",
  "15241": "webp",
  "15242": "webp",
  "15243": "webp",
  "15244": "webp",
  "15252": "webp",
  "15253": "webp",
  "15254": "webp",
  "15255": "webp",
  "15256": "webp",
  "15258": "webp",
  "15259": "webp",
  "15260": "webp",
  "15267": "webp",
  "15268": "webp",
  "15269": "webp",
  "15270": "webp",
  "15271": "webp",
  "15272": "webp",
  "15273": "webp",
  "15274": "webp",
  "15280": "webp",
  "15281": "webp",
  "15284": "webp",
  "15285": "webp",
  "15287": "webp",
  "15288": "webp",
  "15289": "webp",
  "15290": "webp",
  "15291": "webp",
  "15292": "webp",
  "15293": "webp",
  "15294": "webp",
  "15337": "webp",
  "15338": "webp",
  "15339": "jpg",
  "15340": "webp",
  "15603": "jpg",
  "15605": "webp",
  "17204": "webp",
  "17205": "webp",
  "17206": "webp",
  "17207": "webp",
  "17208": "webp",
  "17209": "webp",
  "17210": "webp",
  "19500": "webp",
  "19502": "webp",
  "47101": "jpg",
  "47201": "webp",
  "47202": "webp",
  "47401": "webp",
};

// ── EDL: edl/images — matched by design name (CSV "Code" column) ────────
// "TITAN I" → cloudinary URL
export const EDL_DESIGN_MAP: Record<string, string> = {
  "AFRICAN WOOD": "https://res.cloudinary.com/varindo/image/upload/t5w5qf3apsvnb5zghxoa.png",
  "AFRICAN ZEBRA": "https://res.cloudinary.com/varindo/image/upload/oq01izjt37m9lhxkgfeg.png",
  "AGED PINE": "https://res.cloudinary.com/varindo/image/upload/vzvr2vh48ahclppikyjh.jpg",
  "ALBA MAPLE": "https://res.cloudinary.com/varindo/image/upload/cuehqr7orvovxiyi5hd6.png",
  "ALBATROSS TEAK": "https://res.cloudinary.com/varindo/image/upload/vppezdfa9f9mbyatihux.png",
  "ALBERTA MAPLE": "https://res.cloudinary.com/varindo/image/upload/vg4xagacekwvkjxvw8ew.jpg",
  "ALLOY MATT": "https://res.cloudinary.com/varindo/image/upload/gvha179uhkieoninpz6x.png",
  "ALMOND": "https://res.cloudinary.com/varindo/image/upload/l9gposfjbaylpj6ckohx.png",
  "ALMOST BLUE": "https://res.cloudinary.com/varindo/image/upload/rf8jkk0jjgdhfqyzj53u.png",
  "ALPS": "https://res.cloudinary.com/varindo/image/upload/to0s1jdckl7v3r0earoa.jpg",
  "AMBER SUNSET": "https://res.cloudinary.com/varindo/image/upload/ie1yadpuas8ahmauj4wp.png",
  "AMBERG OAK": "https://res.cloudinary.com/varindo/image/upload/l2zzceb5yljglxkvg6h8.png",
  "ANTICO ROSSO G": "https://res.cloudinary.com/varindo/image/upload/lckmfbmdye5mxrhbas7i.png",
  "ANTICO ROSSO MATT": "https://res.cloudinary.com/varindo/image/upload/j7kdoz8d29ad882nhc6f.jpg",
  "ANTIQUE GREY": "https://res.cloudinary.com/varindo/image/upload/cuwqfwktdbwgnaqfz5kw.png",
  "ANTIQUE OAK": "https://res.cloudinary.com/varindo/image/upload/cdxmk2iotje5kjjcvxaq.jpg",
  "ANTIQUE ROSE": "https://res.cloudinary.com/varindo/image/upload/fi6tpxlhtlwctbhtp0mr.png",
  "ANTIQUE WHITE": "https://res.cloudinary.com/varindo/image/upload/lsh0hotbizqrxgshrv5l.png",
  "AQUILES WALNUT": "https://res.cloudinary.com/varindo/image/upload/vtgjwaghuyjktmhw6i3w.jpg",
  "AREY WALNUT": "https://res.cloudinary.com/varindo/image/upload/sr7ielrymafjqxt8zhzk.png",
  "ARIZONA ELM": "https://res.cloudinary.com/varindo/image/upload/qixaemnuonpmc6ta84a2.png",
  "ARTWALL": "https://res.cloudinary.com/varindo/image/upload/wiq9omka6fjs2vkcjevo.png",
  "ARTWALL ANTHRACITE": "https://res.cloudinary.com/varindo/image/upload/jaxahxgc34kwzho6e0ok.png",
  "ARTWALL GREY": "https://res.cloudinary.com/varindo/image/upload/dld0dhgke1cxf6ztdwfn.jpg",
  "ASH STITCHED LEATHER": "https://res.cloudinary.com/varindo/image/upload/s5nvepezpvrcfohty6uj.png",
  "ASHLEY BLUE": "https://res.cloudinary.com/varindo/image/upload/ojxfxbrdmfsqpubfftuw.png",
  "ATENA GRIGIO": "https://res.cloudinary.com/varindo/image/upload/jxxvaesizg1gqgdfoaid.jpg",
  "AUGUSTA WALNUT": "https://res.cloudinary.com/varindo/image/upload/j8quwbvqg6ksobzajsvb.png",
  "AURA MAPLE": "https://res.cloudinary.com/varindo/image/upload/ljt50lrauudraflqmmhu.jpg",
  "AUSTRIAN CHERRY": "https://res.cloudinary.com/varindo/image/upload/kexd27dxjclfqparoklk.jpg",
  "BABY LEMONADE G": "https://res.cloudinary.com/varindo/image/upload/t6ewwgxniv26fdz3dhk9.jpg",
  "BABY LEMONADE V": "https://res.cloudinary.com/varindo/image/upload/hv8mjptjwkysf9esre6s.png",
  "BAGNARA": "https://res.cloudinary.com/varindo/image/upload/fdhtmlx3z2smn2en3pvi.jpg",
  "BALMY MAPLE": "https://res.cloudinary.com/varindo/image/upload/lk3xawooank1dfphwxff.png",
  "BANAL TEAK": "https://res.cloudinary.com/varindo/image/upload/tx2qwbot7we9sqlgwkqr.png",
  "BARLEY GREY LINE": "https://res.cloudinary.com/varindo/image/upload/mp8ivhkqey8bgqiw3cdv.jpg",
  "BATONNET OAK": "https://res.cloudinary.com/varindo/image/upload/lccuzmvabbhygc6cew7s.png",
  "BEIGE CAMBRIC": "https://res.cloudinary.com/varindo/image/upload/sbq8q7mdtgxs8yirbkna.jpg",
  "BEIGE SEORA OAK": "https://res.cloudinary.com/varindo/image/upload/whngnqec2vfhc7tkuvzv.png",
  "BEIGE TEXTILE": "https://res.cloudinary.com/varindo/image/upload/osg71kbdw7fm7t1prs7e.png",
  "BIANCO G": "https://res.cloudinary.com/varindo/image/upload/hd80kkoqpdapvps0xruj.png",
  "BIANCO V": "https://res.cloudinary.com/varindo/image/upload/ty0r85rhy517l3uqwswa.jpg",
  "BIANCO VENATINO G": "https://res.cloudinary.com/varindo/image/upload/qymdx7fieu7aocfhxgox.jpg",
  "BLACK COSMIC": "https://res.cloudinary.com/varindo/image/upload/bxbht9eq7enhynlfjrmi.png",
  "BLACK FIRENZE": "https://res.cloudinary.com/varindo/image/upload/mlihjphxaqzsnma8mkfp.png",
  "BLACK GALAXY": "https://res.cloudinary.com/varindo/image/upload/p1fdme8hylb8j8rfq02k.jpg",
  "BLACK LATIGO": "https://res.cloudinary.com/varindo/image/upload/f0km4zss1cxvzv7zqwrp.jpg",
  "BLACK ONDE": "https://res.cloudinary.com/varindo/image/upload/lfjgngbnhrhxrraxpzgo.jpg",
  "BLACK PEARL BIRDEYE": "https://res.cloudinary.com/varindo/image/upload/x3ikzrok17tarhlngokl.jpg",
  "BLACK SQUARE BLOCK": "https://res.cloudinary.com/varindo/image/upload/ib1vtyrbomkwwzsrocrw.jpg",
  "BLEEN": "https://res.cloudinary.com/varindo/image/upload/k0ra0l1beyhavy4kkf1m.png",
  "BLEU CLAIR": "https://res.cloudinary.com/varindo/image/upload/rtmzdeuvo8fvh8e2gwz4.png",
  "BLEU VIF": "https://res.cloudinary.com/varindo/image/upload/inxgnm9jaf4u1cnyjvih.png",
  "BOLZANO ELM": "https://res.cloudinary.com/varindo/image/upload/kkqdpyoo5nqbpdwnoqfu.png",
  "BRASS MATT": "https://res.cloudinary.com/varindo/image/upload/n0gub7u0a4iuddfnzbsv.png",
  "BRIX": "https://res.cloudinary.com/varindo/image/upload/lfgii02xdbphco8mkd9h.jpg",
  "BRONZE BRUSH": "https://res.cloudinary.com/varindo/image/upload/a8ppld2rm3aumfyz8ofb.png",
  "BROWN ALBATROSS TEAK": "https://res.cloudinary.com/varindo/image/upload/t8dc8gqgzmqkujyinhlo.jpg",
  "BROWN ASH": "https://res.cloudinary.com/varindo/image/upload/vyxk3nerh1web1ziwn0q.png",
  "BROWN BOLZANO ELM": "https://res.cloudinary.com/varindo/image/upload/vywzd76tsmlqgmdctx47.png",
  "BROWN BONDI BIRCH": "https://res.cloudinary.com/varindo/image/upload/cz5e3syfsixbypkkbkrz.png",
  "BROWN COMBI WOOD": "https://res.cloudinary.com/varindo/image/upload/sflbcj2h0nekxbpwiqmg.png",
  "BROWN PRIM PINE": "https://res.cloudinary.com/varindo/image/upload/mich0htcj3usjah9ly25.jpg",
  "BROWN SHAGBARK HICKORY": "https://res.cloudinary.com/varindo/image/upload/lju5vcw6wiza0plqidog.png",
  "BROWN WOOL": "https://res.cloudinary.com/varindo/image/upload/qnkec2eq4l25fn2xtrgu.png",
  "BURGUNDY": "https://res.cloudinary.com/varindo/image/upload/jfquyp5njcfhzc2haaih.png",
  "BURNT CLAY": "https://res.cloudinary.com/varindo/image/upload/njndcv0buv4lvnppbakz.png",
  "CABANA G": "https://res.cloudinary.com/varindo/image/upload/jeyuqmtes70dku489uu1.png",
  "CABANA MATT": "https://res.cloudinary.com/varindo/image/upload/sfpoew5acrmtdf06lctq.jpg",
  "CALGARY OAK": "https://res.cloudinary.com/varindo/image/upload/motagfjheo5qmgtd1pm8.png",
  "CALIFORNIA TEAK": "https://res.cloudinary.com/varindo/image/upload/s2rqapkidsceskn3its2.jpg",
  "CALM GREY": "https://res.cloudinary.com/varindo/image/upload/wleqhogcnzrpnfjprmzy.png",
  "CANARY": "https://res.cloudinary.com/varindo/image/upload/g9aipdign0cpayz7lew9.png",
  "CAPRICORNUS": "https://res.cloudinary.com/varindo/image/upload/fwdvxbvrbyzx9ifr4afj.jpg",
  "CARBONITE": "https://res.cloudinary.com/varindo/image/upload/jxiasv5cljitap70hfpt.png",
  "CARDOBA": "https://res.cloudinary.com/varindo/image/upload/a0s7llelhp0lhgrq1ckk.png",
  "CARIBBEAN": "https://res.cloudinary.com/varindo/image/upload/vij9ndsx67glgod2ch6h.jpg",
  "CARNICO": "https://res.cloudinary.com/varindo/image/upload/qtzxv4i3uvn0moacswmt.png",
  "CHAMPAGNE BRUSH": "https://res.cloudinary.com/varindo/image/upload/swl7l7sdyfhz2jv2isia.png",
  "CHARTREUSE": "https://res.cloudinary.com/varindo/image/upload/ncdwfdoif4macnmh7maq.png",
  "CHERRY": "https://res.cloudinary.com/varindo/image/upload/cfvqdb52zgw8fbfryl6v.png",
  "CHESTNUT": "https://res.cloudinary.com/varindo/image/upload/rmwza3zknobuweqinxx4.png",
  "CHIARO TRAVERTINO": "https://res.cloudinary.com/varindo/image/upload/ksdew01t2dpmgzsjb1lk.png",
  "CHIFFON ACACIA": "https://res.cloudinary.com/varindo/image/upload/hu8wd6y35nlgu68dnngu.png",
  "CHOCO NAGARE": "https://res.cloudinary.com/varindo/image/upload/tqvirdjopkcoevlw9pyr.png",
  "CHOCO SILK G": "https://res.cloudinary.com/varindo/image/upload/nqverylrywnj9dtmr8lq.png",
  "CHROME MATT": "https://res.cloudinary.com/varindo/image/upload/add50xglohqxyl7ezlsh.png",
  "CIFRA WALNUT": "https://res.cloudinary.com/varindo/image/upload/mf3eia0xnbm84ztqk5a4.png",
  "CLASSIC BLACK": "https://res.cloudinary.com/varindo/image/upload/qegfcc0aaztpgbvxl5de.jpg",
  "CLASSIC OAK": "https://res.cloudinary.com/varindo/image/upload/fti6nbexgxlgxicbejsn.png",
  "CLASSIC WHITE": "https://res.cloudinary.com/varindo/image/upload/iiqt0t8n3lmgrzseacbr.jpg",
  "CLAY AREY WALNUT": "https://res.cloudinary.com/varindo/image/upload/prulgurskf9pi7evcn8d.png",
  "CLEAR MAPLE": "https://res.cloudinary.com/varindo/image/upload/mzvqatxikg3gvj27g1hg.png",
  "CLOUD": "https://res.cloudinary.com/varindo/image/upload/ssepp5wtajm5ss7oio8o.jpg",
  "CLOUDY BROWN 10FT": "https://res.cloudinary.com/varindo/image/upload/isleik3ed4fgjwbl4xai.png",
  "CLOUDY BROWN 8FT": "https://res.cloudinary.com/varindo/image/upload/mgidpcbjr86fhezn2ktf.png",
  "COBBLED LORENZA WALNUT": "https://res.cloudinary.com/varindo/image/upload/h5lr8que8jrllxt2urru.jpg",
  "COCOA STITCHED LEATHER": "https://res.cloudinary.com/varindo/image/upload/k31brhhcc2m9asiladsh.jpg",
  "COMBI ROVERE": "https://res.cloudinary.com/varindo/image/upload/nnnhuw4kxoxiekosxmtm.png",
  "COOL WHITE G": "https://res.cloudinary.com/varindo/image/upload/imetq4gdglopzkhizrqi.png",
  "COOL WHITE V": "https://res.cloudinary.com/varindo/image/upload/blslpbc3d4tu8blrzqvu.png",
  "COPPER BRUSH": "https://res.cloudinary.com/varindo/image/upload/acdoejverwsqsaq4igqu.png",
  "COPPER GALAXY": "https://res.cloudinary.com/varindo/image/upload/cdfazgp9dokqhuqagimo.png",
  "CORDELIA REFINED": "https://res.cloudinary.com/varindo/image/upload/qeptbizilkm2vinukcbh.jpg",
  "COSMOPOLITAN": "https://res.cloudinary.com/varindo/image/upload/ujsrkuju1ztg986r1zh4.jpg",
  "COTTON FLUFF": "https://res.cloudinary.com/varindo/image/upload/ps0iwkxv7jebhqvmez5w.png",
  "CREAM GRAPHIC": "https://res.cloudinary.com/varindo/image/upload/pjyzoz3ht6eibzxdojsd.jpg",
  "CROCHET DAWN": "https://res.cloudinary.com/varindo/image/upload/nazc2vuxwmaavjrj9y1q.jpg",
  "CROCHET DUSK": "https://res.cloudinary.com/varindo/image/upload/ptawyrt1yidoukwe3o7r.png",
  "CRYSTAL GREY": "https://res.cloudinary.com/varindo/image/upload/jfg9alwlauvrtsdroyya.jpg",
  "CRYSTAL SATIN": "https://res.cloudinary.com/varindo/image/upload/fjtowq4ixct0raxcb5wh.jpg",
  "DALI GRAU": "https://res.cloudinary.com/varindo/image/upload/cvtgbqi0eat5mby9t84q.jpg",
  "DANISH WALNUT": "https://res.cloudinary.com/varindo/image/upload/myvk7yelenmk21e9gjzs.png",
  "DARK ALBA MAPLE": "https://res.cloudinary.com/varindo/image/upload/szlm5tzc7oikchytqonr.png",
  "DARK AMBERG OAK": "https://res.cloudinary.com/varindo/image/upload/oapxw0dojnyooj21wehx.jpg",
  "DARK ASH": "https://res.cloudinary.com/varindo/image/upload/bu7arm0f0gwe2dquozgw.png",
  "DARK AUGUSTA WALNUT": "https://res.cloudinary.com/varindo/image/upload/ue5b7agzyctli1m9oiv3.png",
  "DARK EBONY": "https://res.cloudinary.com/varindo/image/upload/cc8omaerrp06rmgzvobs.png",
  "DARK ERABLE": "https://res.cloudinary.com/varindo/image/upload/nqivqhs4x2gqxidzhbrq.png",
  "DARK GRAPHIC": "https://res.cloudinary.com/varindo/image/upload/tbqowkuf6vtmvacrggf7.png",
  "DARK HARMA ASH": "https://res.cloudinary.com/varindo/image/upload/drzklmhnalidkdgrnabx.png",
  "DARK HARRIS WALNUT": "https://res.cloudinary.com/varindo/image/upload/acjqmar7hxxtjiwyy74w.png",
  "DARK HARVARD OAK": "https://res.cloudinary.com/varindo/image/upload/q1ynnbx20durdx8xyjhs.jpg",
  "DARK HIPSTER OAK": "https://res.cloudinary.com/varindo/image/upload/egdjak4cdj0ry0njryqk.png",
  "DARK JAZZ OAK": "https://res.cloudinary.com/varindo/image/upload/sfz9qaetg9fkmtt7l7rd.png",
  "DARK JOONA TEAK": "https://res.cloudinary.com/varindo/image/upload/w2jnx23sr72uxgsp7eo3.png",
  "DARK KATOVIK NOCE": "https://res.cloudinary.com/varindo/image/upload/va7pxqp7c3ce5vnmuku7.png",
  "DARK LAMINA": "https://res.cloudinary.com/varindo/image/upload/mfxtnvvuj2rdt00mre63.png",
  "DARK LAVANT MATT": "https://res.cloudinary.com/varindo/image/upload/hhiiogo83q0hzqpfbgnu.jpg",
  "DARK MAGENTA": "https://res.cloudinary.com/varindo/image/upload/jhsy4amkxene30e3yfiv.jpg",
  "DARK MONTFORT ELM": "https://res.cloudinary.com/varindo/image/upload/caybaqxhpilo3pnfmone.png",
  "DARK MUSE G": "https://res.cloudinary.com/varindo/image/upload/dwujswqslg7yjmmljmtc.jpg",
  "DARK NICO BEECH": "https://res.cloudinary.com/varindo/image/upload/secit4l3j0qfnsnxz57n.png",
  "DARK PARMA WALNUT": "https://res.cloudinary.com/varindo/image/upload/wyatugecrwcuw6thue1z.png",
  "DARK SILVER BRUSH": "https://res.cloudinary.com/varindo/image/upload/injhemk9atfbt2wp9okb.png",
  "DARK STYLISH TEAK": "https://res.cloudinary.com/varindo/image/upload/kwbls85nrinhtofrfoox.png",
  "DARK VEYRE OAK": "https://res.cloudinary.com/varindo/image/upload/ekqd1b6hydnsjv2o9d76.png",
  "DARK VIOLET": "https://res.cloudinary.com/varindo/image/upload/x8ttfeajgczyjtczanxu.jpg",
  "DAYLIGHT 10FT": "https://res.cloudinary.com/varindo/image/upload/we7lhmuesddf3ueyge29.png",
  "DAYLIGHT 8FT": "https://res.cloudinary.com/varindo/image/upload/as7plthoq3cjli7qr6on.jpg",
  "DELAWARE": "https://res.cloudinary.com/varindo/image/upload/ozft3lnrhbzpf3a081gz.jpg",
  "DENVER OAK": "https://res.cloudinary.com/varindo/image/upload/d3nbs09a2gvjtsgrqb1m.png",
  "DOTTI BLACK": "https://res.cloudinary.com/varindo/image/upload/reh606tp7aepdh3p1ner.png",
  "DOUBLE CREAM": "https://res.cloudinary.com/varindo/image/upload/srylnxqae0debeqzewk4.jpg",
  "DUERO WALNUT": "https://res.cloudinary.com/varindo/image/upload/s8m9grndqk1c03hhsrbt.png",
  "DUFF": "https://res.cloudinary.com/varindo/image/upload/a8z8l1wvzxcpjf98wxlr.jpg",
  "DUSTY BLUE LINE": "https://res.cloudinary.com/varindo/image/upload/kzvn2yzzbmvxmihfyfl3.png",
  "EASTERN ALDER": "https://res.cloudinary.com/varindo/image/upload/iegfozadoxujthdnzwju.png",
  "ECHSE": "https://res.cloudinary.com/varindo/image/upload/emgthegb4tyqvr9wxbn8.jpg",
  "ELEGANCE BROWN": "https://res.cloudinary.com/varindo/image/upload/gnrcggujnj9zd7tckf0k.png",
  "ELEGANCE GREY": "https://res.cloudinary.com/varindo/image/upload/fxyxcldgksdpbbmpsrtn.jpg",
  "ELEGANCE NATURAL": "https://res.cloudinary.com/varindo/image/upload/dfnbj7h329yc4v2uljvm.jpg",
  "ELEMENT": "https://res.cloudinary.com/varindo/image/upload/cs6p1u2r50qchjdikp5v.png",
  "ENDLESS OAK BLACK": "https://res.cloudinary.com/varindo/image/upload/ejxhxrv7egpwrw6gjorc.png",
  "ENDLESS OAK NATURAL": "https://res.cloudinary.com/varindo/image/upload/xf8t8losbwftesm01rld.png",
  "ENGLISH OAK": "https://res.cloudinary.com/varindo/image/upload/concd9drbzzuitmwzfhx.png",
  "ESPRESSO BROWN V": "https://res.cloudinary.com/varindo/image/upload/o9bqijcgyjuok4odyn1s.png",
  "ETNA OAK": "https://res.cloudinary.com/varindo/image/upload/jxi4oeauv1rpbdb9l2al.png",
  "EXQUISITE DARK": "https://res.cloudinary.com/varindo/image/upload/pbqwbpshobwe2rkrwhbg.png",
  "EXQUISITE LIGHT": "https://res.cloudinary.com/varindo/image/upload/b4ubnnml6kkgsgho1pzk.png",
  "FAINT BEECH": "https://res.cloudinary.com/varindo/image/upload/djvwpnbd6gfkzhb3q2fw.png",
  "FANGO": "https://res.cloudinary.com/varindo/image/upload/kpwvm7dv1jx23pw551xg.jpg",
  "FLAMINGO": "https://res.cloudinary.com/varindo/image/upload/jdilrtsosc7pmkmkzldn.png",
  "FLANNEL CHERRY": "https://res.cloudinary.com/varindo/image/upload/a0eqdl5vpuir2ax6jwxf.png",
  "FOCUS GREY": "https://res.cloudinary.com/varindo/image/upload/mriwea0ekrv8p9hbhgce.png",
  "FOCUS GREY MAGNETIC": "https://res.cloudinary.com/varindo/image/upload/xhb6sdsy122znehhqq7j.jpg",
  "FOG": "https://res.cloudinary.com/varindo/image/upload/w3r2u7casahntawidlr7.jpg",
  "FRESCO WALNUT": "https://res.cloudinary.com/varindo/image/upload/g69xfo66ga2tooho41dc.jpg",
  "FUDGE": "https://res.cloudinary.com/varindo/image/upload/uhzltnr7ra3hpapzqmlg.png",
  "FUNKY BLACK": "https://res.cloudinary.com/varindo/image/upload/epo9vsiwqmwfjsinupkk.png",
  "FUYU": "https://res.cloudinary.com/varindo/image/upload/t8j0yhitjxq4e1mtwwrd.png",
  "GEMINI": "https://res.cloudinary.com/varindo/image/upload/efko27li5lm4u6uogngh.png",
  "GINGER ALE": "https://res.cloudinary.com/varindo/image/upload/qdheviun0fadbuabnpqq.png",
  "GLAZED GALAXY": "https://res.cloudinary.com/varindo/image/upload/vdvk3glzlfsrwkdazvog.png",
  "GOLD BRUSH": "https://res.cloudinary.com/varindo/image/upload/vzfle7z33wf0kdvrzjko.png",
  "GOLD GALAXY": "https://res.cloudinary.com/varindo/image/upload/s5jfprbs2kaf4qptkxmw.png",
  "GOLDEN MAPLE": "https://res.cloudinary.com/varindo/image/upload/iqawz9vv88fisml0jdix.png",
  "GRANITE GREY": "https://res.cloudinary.com/varindo/image/upload/pi9n0lecgater5jm5dai.png",
  "GRAPHITE": "https://res.cloudinary.com/varindo/image/upload/upokwcquhaq5byc7b65p.jpg",
  "GREY ARIZONA ELM": "https://res.cloudinary.com/varindo/image/upload/agjik3qmeyv7tggq1a3h.png",
  "GREY BOLZANO ELM": "https://res.cloudinary.com/varindo/image/upload/bnvcpgxg1cqievma2kt3.png",
  "GREY COMBI WOOD": "https://res.cloudinary.com/varindo/image/upload/rc2gzvr8py5myz3mcaa2.jpg",
  "GREY GALAXY": "https://res.cloudinary.com/varindo/image/upload/r6pogzqjlslq3c5a4zak.png",
  "GREY JAZZ OAK": "https://res.cloudinary.com/varindo/image/upload/xfxmtuwcybavpchrcscx.png",
  "GREY MACQUARIE MAPLE": "https://res.cloudinary.com/varindo/image/upload/nojwjeihp8gypqip08su.jpg",
  "GREY MONTFORT ELM": "https://res.cloudinary.com/varindo/image/upload/jbktpv15hkes9zcgnrse.jpg",
  "GREY SHAGBARK HICKORY": "https://res.cloudinary.com/varindo/image/upload/b926iuvqiw4wodlemwwk.png",
  "GREY STITCHED LEATHER": "https://res.cloudinary.com/varindo/image/upload/rxvrvywuh6b3qpw509xn.jpg",
  "GREY WOOL": "https://res.cloudinary.com/varindo/image/upload/msnqougzrllg3iflcp8w.png",
  "GREYISH WENGE": "https://res.cloudinary.com/varindo/image/upload/uhumt32igclhdzmfu4jk.jpg",
  "HABSBURG OAK": "https://res.cloudinary.com/varindo/image/upload/tjnirb9v3w3fww67bpmp.png",
  "HANDY GREY": "https://res.cloudinary.com/varindo/image/upload/damihdsv49fwnzvsgoxb.png",
  "HARDROCK MAPLE": "https://res.cloudinary.com/varindo/image/upload/tl7yhhbtjejvd5evmeo9.png",
  "HARMA ASH": "https://res.cloudinary.com/varindo/image/upload/w1prqlrtpq4olkfwezhp.png",
  "HARRIS WALNUT": "https://res.cloudinary.com/varindo/image/upload/gj7pik53s6adszqjpvhx.png",
  "HAZEL ACACIA": "https://res.cloudinary.com/varindo/image/upload/mqyvtkdd374skapfyaeg.png",
  "HAZEL BRONZE MATT": "https://res.cloudinary.com/varindo/image/upload/rbni2ttdugtfxflgdk9g.png",
  "HELIO GREY": "https://res.cloudinary.com/varindo/image/upload/ubyw8ohq1fg3c1mjbmef.png",
  "HEMLOCK": "https://res.cloudinary.com/varindo/image/upload/gkbhbxrdjtbyt4nwiq5i.jpg",
  "HESSIAN LIGHT": "https://res.cloudinary.com/varindo/image/upload/i4f6770ljxfgyvrg7nev.png",
  "HICKORY": "https://res.cloudinary.com/varindo/image/upload/jjaoqnfejoqsnb7hcnft.png",
  "HICKORY ARIA": "https://res.cloudinary.com/varindo/image/upload/i7d0iqbwsnz6lilpf08x.jpg",
  "HICKORY CRISP": "https://res.cloudinary.com/varindo/image/upload/d2pnpkmrgv41mdhydgyf.png",
  "HICKORY WISP": "https://res.cloudinary.com/varindo/image/upload/upgtadhipu5u34jozmhy.jpg",
  "HIPSTER OAK": "https://res.cloudinary.com/varindo/image/upload/r82bucqny4mf9hxya9kq.png",
  "HOOPER BLAU": "https://res.cloudinary.com/varindo/image/upload/qkhfrondbinefqhtlsmv.jpg",
  "IBSEN BEECH": "https://res.cloudinary.com/varindo/image/upload/m4goe6t1kyukb3ousfxf.jpg",
  "ICELAND MAPLE": "https://res.cloudinary.com/varindo/image/upload/ajiusurqxrnmp9nkkpqy.jpg",
  "INDIAN EBONY": "https://res.cloudinary.com/varindo/image/upload/qtwu4ueor3ury157plpo.jpg",
  "IRISH ALMOND": "https://res.cloudinary.com/varindo/image/upload/dh1dptaa0hakhcw7ncvn.png",
  "ITALIAN CHESTNUT": "https://res.cloudinary.com/varindo/image/upload/bzbjlb7bhinke6cj9te1.png",
  "IVOIRE": "https://res.cloudinary.com/varindo/image/upload/m3rsp8maqc3gaeecu8cx.png",
  "IVORY BRUSH": "https://res.cloudinary.com/varindo/image/upload/j3575eei3vdqpzhjp6bj.png",
  "JAFFA ORANGE": "https://res.cloudinary.com/varindo/image/upload/excwkzycpm44welbrh6c.png",
  "JAZZ OAK": "https://res.cloudinary.com/varindo/image/upload/x5la4afrap5trbkizhnz.png",
  "JOONA TEAK": "https://res.cloudinary.com/varindo/image/upload/mppj2mocutzjlldcgz1x.jpg",
  "KATOVIK NOCE": "https://res.cloudinary.com/varindo/image/upload/hdmqrtbflok6jhqmpmeb.png",
  "KATTHULT SM": "https://res.cloudinary.com/varindo/image/upload/wddcv3ndtnrinkhxn08c.png",
  "KAUAI HICKORY": "https://res.cloudinary.com/varindo/image/upload/ojknxyiayyykhflkhgv1.jpg",
  "KIESEL": "https://res.cloudinary.com/varindo/image/upload/ttax28f6cd1yiwliba1p.jpg",
  "LACE WHITE G": "https://res.cloudinary.com/varindo/image/upload/w8upvqh2dlteqogt0tzy.jpg",
  "LACE WHITE V": "https://res.cloudinary.com/varindo/image/upload/li3pmvflscriev38l3l0.jpg",
  "LAVANT G": "https://res.cloudinary.com/varindo/image/upload/i0guv5uoirbpt11hdjho.jpg",
  "LAWN GREEN": "https://res.cloudinary.com/varindo/image/upload/cg285owo8pa7ghvxhvpu.jpg",
  "LEGARTO OAK": "https://res.cloudinary.com/varindo/image/upload/motd0vrnisjjqe0cza72.png",
  "LEMON GREEN": "https://res.cloudinary.com/varindo/image/upload/tjzqrh7vlthtpizwrlfm.png",
  "LIGHT ALBATROSS TEAK": "https://res.cloudinary.com/varindo/image/upload/enzfmbh1vpv6uzwk0ldd.png",
  "LIGHT ARIZONA ELM": "https://res.cloudinary.com/varindo/image/upload/t43pxrsyr6jfbezstvkd.png",
  "LIGHT ASH": "https://res.cloudinary.com/varindo/image/upload/gto9wqlkffrg4ytorktr.jpg",
  "LIGHT BLEU CLAIR": "https://res.cloudinary.com/varindo/image/upload/h287m9iiq0nspmcu5x8m.png",
  "LIGHT BOLZANO ELM": "https://res.cloudinary.com/varindo/image/upload/aks1wekyljuswpzow85a.jpg",
  "LIGHT ELM": "https://res.cloudinary.com/varindo/image/upload/oi7psgpouuckuuj90x3i.png",
  "LIGHT HIPSTER OAK": "https://res.cloudinary.com/varindo/image/upload/lmnwtw3lgz3s0ouldv9q.jpg",
  "LIGHT LAMINA": "https://res.cloudinary.com/varindo/image/upload/vldmzgddt9mub1rhxxcr.jpg",
  "LIGHT MACQUARIE MAPLE": "https://res.cloudinary.com/varindo/image/upload/qitoarryn2pftwn0ct5x.png",
  "LIGHT MEDITERRANEAN": "https://res.cloudinary.com/varindo/image/upload/xinj2qg048pwsvtgjrgw.jpg",
  "LIGHT ORCHID": "https://res.cloudinary.com/varindo/image/upload/kr0d2ylr1lmhhwotvxbs.png",
  "LIGHT PRIM PINE": "https://res.cloudinary.com/varindo/image/upload/c0d2habyf5whkzccomcq.png",
  "LIGHT RODEZ OAK": "https://res.cloudinary.com/varindo/image/upload/vab6s8xchjpaymp5xbni.png",
  "LIGHT SHAGBARK HICKORY": "https://res.cloudinary.com/varindo/image/upload/c1mgpmw3xs58a29s2q52.png",
  "LIGHT VEYRE OAK": "https://res.cloudinary.com/varindo/image/upload/jdzlnrlregquwxjjjjg3.png",
  "LIGHT WAJAR OAK": "https://res.cloudinary.com/varindo/image/upload/h0bj6tprwv9omdj5ltqk.jpg",
  "LIGHT WALK THE LINE": "https://res.cloudinary.com/varindo/image/upload/lo466kgj7pb6q4jo2uo7.jpg",
  "LIME FIZZ": "https://res.cloudinary.com/varindo/image/upload/pv5ub1hudxqgjskvqxmh.jpg",
  "LIME GREEN": "https://res.cloudinary.com/varindo/image/upload/mimeaffajk2bb9zasqih.jpg",
  "LINE BLACK": "https://res.cloudinary.com/varindo/image/upload/enyz8kt9e4nbxyhsuomg.png",
  "LINE WHITE": "https://res.cloudinary.com/varindo/image/upload/wo0cchpg7udgo0uywzpk.png",
  "LINEN WALK THE LINE": "https://res.cloudinary.com/varindo/image/upload/irjopepl3uoatlnjjmkr.png",
  "LINEN WHITE": "https://res.cloudinary.com/varindo/image/upload/lnvc7k0kbgnr89toovah.jpg",
  "LINON ELM": "https://res.cloudinary.com/varindo/image/upload/elbgiu5uoqwgyhlgoaa9.png",
  "LORENZA WALNUT": "https://res.cloudinary.com/varindo/image/upload/cmyatau8hytn8nqkejtl.jpg",
  "LORRIANE WALNUT": "https://res.cloudinary.com/varindo/image/upload/dhbrk6bfjloioqzufsal.jpg",
  "LUSERNA GRIGIO": "https://res.cloudinary.com/varindo/image/upload/wygfgrgctwc4bgfzfnjd.png",
  "LUSERNA NERO": "https://res.cloudinary.com/varindo/image/upload/bg0h5heczjajw9ukinie.png",
  "MACQUARIE MAPLE": "https://res.cloudinary.com/varindo/image/upload/jbhfuqcc6rsqoawxr5y3.png",
  "MALEVICH IVORY": "https://res.cloudinary.com/varindo/image/upload/tlfrccoil7vksxel21d3.jpg",
  "MALTA CHIARA": "https://res.cloudinary.com/varindo/image/upload/taqqxzdgdc6m6smdv8vv.png",
  "MALTA CHIARA 10FT": "https://res.cloudinary.com/varindo/image/upload/kmxcbwypgz0l1qsvmmsi.png",
  "MALTA FONDO 10FT": "https://res.cloudinary.com/varindo/image/upload/q0s6dazwc0txqj7v2q8d.png",
  "MALTA LIEVE": "https://res.cloudinary.com/varindo/image/upload/vi5s9q8m0q3k3xkvnatg.png",
  "MALTA LIEVE 10FT": "https://res.cloudinary.com/varindo/image/upload/x2eeyjjf34xdgolsazqf.png",
  "MALTA SOTTILE 10FT": "https://res.cloudinary.com/varindo/image/upload/hr7ielmnfexv3bzq6cts.png",
  "MANDARIN": "https://res.cloudinary.com/varindo/image/upload/txlnrmwqeqf3kn9kqunw.png",
  "MAPUCHE BEIGE": "https://res.cloudinary.com/varindo/image/upload/xfrz2uy5ashsstlpujg2.jpg",
  "MARBLE BIANCO": "https://res.cloudinary.com/varindo/image/upload/tjwqry0uk1quqlxfbhob.png",
  "MARINA": "https://res.cloudinary.com/varindo/image/upload/wxiipsx1f8icmrzjjqfh.jpg",
  "MAROON GALAXY": "https://res.cloudinary.com/varindo/image/upload/xjre4tuwbozmg3cviavy.jpg",
  "MATCHA": "https://res.cloudinary.com/varindo/image/upload/qpextbmdjmqocfm5ikjl.png",
  "MEDITERRANEAN": "https://res.cloudinary.com/varindo/image/upload/wtrcqzzj1zh95cvqt2wo.jpg",
  "MEDIUM ELM": "https://res.cloudinary.com/varindo/image/upload/ddepo9yxqib9e7h3osio.jpg",
  "MEDIUM HIPSTER OAK": "https://res.cloudinary.com/varindo/image/upload/tdjgso6kxjx3bmlfw7kp.jpg",
  "MEDIUM MONTFORT ELM": "https://res.cloudinary.com/varindo/image/upload/mlj0cvemjpawji2rtagw.png",
  "MEDIUM PURPLE": "https://res.cloudinary.com/varindo/image/upload/qnkenligzczpbiu0awoo.png",
  "MEMPHIS CLASSIC": "https://res.cloudinary.com/varindo/image/upload/ta928hymhcvntykdezmr.jpg",
  "MERINO": "https://res.cloudinary.com/varindo/image/upload/p6ipzquus5gcdzomwexx.png",
  "MIDNIGHT GREY 10FT": "https://res.cloudinary.com/varindo/image/upload/fnx8wdwxmq1hplcdwdy9.png",
  "MIDNIGHT GREY 8FT": "https://res.cloudinary.com/varindo/image/upload/qqbssovlrjzytybsjxms.png",
  "MILAN OAK": "https://res.cloudinary.com/varindo/image/upload/il1kelcvxixovzhkqt49.png",
  "MILAN WHITE": "https://res.cloudinary.com/varindo/image/upload/wfy2iqj1alw13iefpnnv.png",
  "MILD BEIGE": "https://res.cloudinary.com/varindo/image/upload/qwwbxhdkmmwtvhbgpwjh.jpg",
  "MINDFUL CREAM": "https://res.cloudinary.com/varindo/image/upload/qwbw1kkj8bt03hfyl0a6.jpg",
  "MISSION WHITE": "https://res.cloudinary.com/varindo/image/upload/tbghbewm9epg1bdkjlkg.png",
  "MISTY": "https://res.cloudinary.com/varindo/image/upload/noq1jynyypyv0lclsxgp.png",
  "MOCA ALBATROSS TEAK": "https://res.cloudinary.com/varindo/image/upload/esnthdtfmny6y2azdgds.png",
  "MOCCA OAK": "https://res.cloudinary.com/varindo/image/upload/e8efdzvt1uv0a9ylg6hv.png",
  "MOCHA": "https://res.cloudinary.com/varindo/image/upload/mnihqotzcy5a0b7hhrqz.png",
  "MONTFORT ELM": "https://res.cloudinary.com/varindo/image/upload/ihgsb6qoofejaybvjedy.png",
  "MOONLIGHT GREY 10FT": "https://res.cloudinary.com/varindo/image/upload/hvngnag1fkyrpb96fbvl.jpg",
  "MOONLIGHT GREY 8FT": "https://res.cloudinary.com/varindo/image/upload/qvddpl6hzdiimdwa8uay.jpg",
  "MOONSCAPE WHITE": "https://res.cloudinary.com/varindo/image/upload/hjz6yqyvq1spuomlm5al.png",
  "MOSS GREEN": "https://res.cloudinary.com/varindo/image/upload/nbwqcuqdgn1uux5f4pwd.png",
  "MUSTARD GOLD": "https://res.cloudinary.com/varindo/image/upload/vw9t9eg7jib18tpgvcua.jpg",
  "MUTED OLIVE": "https://res.cloudinary.com/varindo/image/upload/tnc1fycq9h1djk3f6bc5.png",
  "NAGARE YOKO I": "https://res.cloudinary.com/varindo/image/upload/do5a9e1uciezx8yjhxsb.jpg",
  "NAGARE YOKO II": "https://res.cloudinary.com/varindo/image/upload/ee7rhl15dcawz6ue1tvq.jpg",
  "NAGARE YOKO III": "https://res.cloudinary.com/varindo/image/upload/pmhjn8u1f8rvtavv5gw5.png",
  "NAPPA": "https://res.cloudinary.com/varindo/image/upload/e0qoiu3i0npupxmoh3kw.png",
  "NATURAL BEECH": "https://res.cloudinary.com/varindo/image/upload/s2x2ds8ebrxxfmk74abj.png",
  "NATURAL CONCRETE": "https://res.cloudinary.com/varindo/image/upload/dckvzvuz7b3r4hfossaq.png",
  "NATURAL MAPLE": "https://res.cloudinary.com/varindo/image/upload/baugvqtqis0fkqm8a5b6.png",
  "NATURAL MAPLE 1": "https://res.cloudinary.com/varindo/image/upload/ecxntf1i6nyha3lommty.png",
  "NATURAL SYLVAN WALNUT": "https://res.cloudinary.com/varindo/image/upload/dg5rdk77wel98eou0w16.png",
  "NATURAL WAJAR OAK": "https://res.cloudinary.com/varindo/image/upload/gfmnqp3fjdjeu8ixp8sl.png",
  "NATURAL WENGE": "https://res.cloudinary.com/varindo/image/upload/tnmglk8ixmtktloibijz.png",
  "NERO MORAINE G": "https://res.cloudinary.com/varindo/image/upload/foq1mutwbkrjf8rkbzqa.jpg",
  "NERO MORAINE MATT": "https://res.cloudinary.com/varindo/image/upload/fgwwoecqdceiaa3xcn9q.jpg",
  "NERO ROSSO G": "https://res.cloudinary.com/varindo/image/upload/a6rxmciaiygit2kmmofw.jpg",
  "NERO TRAVERTINO": "https://res.cloudinary.com/varindo/image/upload/vdq9ggw9bkjxaze19odq.png",
  "NEUTRAL KATOVIK NOCE": "https://res.cloudinary.com/varindo/image/upload/eq7qhbe0ivo0dnzjx177.png",
  "NEUTRAL WEBSTER OAK": "https://res.cloudinary.com/varindo/image/upload/o8t31t2dyuxr6tpyucgl.png",
  "NEW TEAK": "https://res.cloudinary.com/varindo/image/upload/akpsmjbxkyyof5rrzkxa.png",
  "NIGERIA B": "https://res.cloudinary.com/varindo/image/upload/ilkngl1afhzsawp99vzr.jpg",
  "NOA MARBLE G": "https://res.cloudinary.com/varindo/image/upload/abacp5eeipp4egrdxmrk.png",
  "NOA MARBLE MATT": "https://res.cloudinary.com/varindo/image/upload/iy6i0yiv28fphwbavxvb.jpg",
  "NOBLE LUX": "https://res.cloudinary.com/varindo/image/upload/boruqar9e651mmmosad8.png",
  "NOBLE MOCHA": "https://res.cloudinary.com/varindo/image/upload/gs0fbuq04fe4hdlnyme8.png",
  "NOCE CENDRE": "https://res.cloudinary.com/varindo/image/upload/huvgyqcgjaavysrkrvha.jpg",
  "NOIR 10FT": "https://res.cloudinary.com/varindo/image/upload/cvfrufmcpimrz365j3ri.png",
  "NOIR 8FT": "https://res.cloudinary.com/varindo/image/upload/k0afycly5phdmg0ptjbi.jpg",
  "NOVA KATOVIK NOCE": "https://res.cloudinary.com/varindo/image/upload/ek0sx42euyj312qe3ffh.png",
  "NUDE BLUSH": "https://res.cloudinary.com/varindo/image/upload/pvuauqnkxcdsce3k4ypi.png",
  "OAT": "https://res.cloudinary.com/varindo/image/upload/lbyltlof6wm55tgo4xgr.png",
  "ONTARIA OAK": "https://res.cloudinary.com/varindo/image/upload/xih2u6mplghbuxpoj7o3.jpg",
  "ORANGE": "https://res.cloudinary.com/varindo/image/upload/skx6lkij7rr7eetwyamv.png",
  "ORANGE PEEL": "https://res.cloudinary.com/varindo/image/upload/w7ryc3yw7fvoapsixits.jpg",
  "ORANGE RED": "https://res.cloudinary.com/varindo/image/upload/dj2uuu5egdfgldxe6muw.png",
  "ORGANIC STONE": "https://res.cloudinary.com/varindo/image/upload/msok7xxmedb5hwo4tw0r.png",
  "OYSTER GREY": "https://res.cloudinary.com/varindo/image/upload/adl1w7kqrpfgbvhxzdur.png",
  "PARMA WALNUT": "https://res.cloudinary.com/varindo/image/upload/vbjb3vvewfqkuj77wja7.jpg",
  "PEARL BIANCO": "https://res.cloudinary.com/varindo/image/upload/l8exphksldi9aunr4rml.jpg",
  "PEARL CALACATTA G": "https://res.cloudinary.com/varindo/image/upload/rwpsmwu8eda7ruacqg3d.png",
  "PEARL GREY V": "https://res.cloudinary.com/varindo/image/upload/llisye44hmmf5snalvkw.png",
  "PEARL HORIZON": "https://res.cloudinary.com/varindo/image/upload/fdajry07blkgjqcktwhr.png",
  "PEARL REFLEX": "https://res.cloudinary.com/varindo/image/upload/v5yyatvx46ra3zbdmro9.png",
  "PEARL WHITE": "https://res.cloudinary.com/varindo/image/upload/trwp4ckox23zhahtaztc.png",
  "PERLA TRAVERTINO": "https://res.cloudinary.com/varindo/image/upload/xlylc3iqzzlepwsawfuf.png",
  "PERSE": "https://res.cloudinary.com/varindo/image/upload/rdamgs1hwpkli7wamlho.jpg",
  "PESARO": "https://res.cloudinary.com/varindo/image/upload/lneufudoyqlprsgp6hkf.jpg",
  "PHANTOM BLACK": "https://res.cloudinary.com/varindo/image/upload/ppy1axdxhstxieyqrhuf.jpg",
  "PIANO BLACK": "https://res.cloudinary.com/varindo/image/upload/cq5faesx018jk85wk2lw.png",
  "PIANO BLACK 1.0MM": "https://res.cloudinary.com/varindo/image/upload/a3xya0fu6faozhqe2b4r.png",
  "PIANO WHITE": "https://res.cloudinary.com/varindo/image/upload/dbllb6tc7nuvs1wssgm7.jpg",
  "PIANO WHITE 1.0MM": "https://res.cloudinary.com/varindo/image/upload/rmhvok4pible20sm0f6g.jpg",
  "PIERZ G": "https://res.cloudinary.com/varindo/image/upload/vnmfequoryapaxx5vbj0.jpg",
  "PIERZ MATT": "https://res.cloudinary.com/varindo/image/upload/ipp708w6xnroctaj07px.png",
  "PISCES": "https://res.cloudinary.com/varindo/image/upload/o3ptekxkybthhdeuwuru.png",
  "PISTACHIO GREEN G": "https://res.cloudinary.com/varindo/image/upload/qiwut5s36vinlfz25zpp.png",
  "PISTACHIO GREEN V": "https://res.cloudinary.com/varindo/image/upload/t0ywluivkphpp77snuxb.png",
  "POLAR WHITE": "https://res.cloudinary.com/varindo/image/upload/fiv4kcfcial7mgpcetfv.jpg",
  "POLISH GREY LINE": "https://res.cloudinary.com/varindo/image/upload/vk6yhas33vpbgpwfdshg.png",
  "POLISHED GREY MIRROR": "https://res.cloudinary.com/varindo/image/upload/acbcqphei7gcegbsdlnh.png",
  "POLLOCK GRAU": "https://res.cloudinary.com/varindo/image/upload/bzlja7aplofjlmlvcxvx.jpg",
  "POPLAR MARACUYA": "https://res.cloudinary.com/varindo/image/upload/fipvm07irzlasgyrmzqf.jpg",
  "PORCELAIN": "https://res.cloudinary.com/varindo/image/upload/ufgyinfezxsdk4mg2nuc.png",
  "PORCELEIN TEAK": "https://res.cloudinary.com/varindo/image/upload/bog5bpzljqlj9r3b8gz8.png",
  "PUMICE": "https://res.cloudinary.com/varindo/image/upload/vle8ajfyuzmf6hhh4kfq.jpg",
  "PURE GREY": "https://res.cloudinary.com/varindo/image/upload/hvx00s7r7cjbayiylnpb.png",
  "QUARTZITE": "https://res.cloudinary.com/varindo/image/upload/ewi2phjeljnfmnplobbp.jpg",
  "RAW HIPSTER OAK": "https://res.cloudinary.com/varindo/image/upload/bv7x9xmfe5sbbhdz15ge.png",
  "RAW LORENZA WALNUT": "https://res.cloudinary.com/varindo/image/upload/gsbljzbkostimalapvo2.png",
  "REGENCY CHERRY": "https://res.cloudinary.com/varindo/image/upload/vcrttlhagre0rr1vcsaa.jpg",
  "RODEZ OAK": "https://res.cloudinary.com/varindo/image/upload/h6blcicudrsaeofbawd9.png",
  "ROLA CLOUD": "https://res.cloudinary.com/varindo/image/upload/n0efa8gdtwr82log33yp.png",
  "ROLA TERRA": "https://res.cloudinary.com/varindo/image/upload/k0mgrcktssgdr7adikim.png",
  "ROSA STONE": "https://res.cloudinary.com/varindo/image/upload/bivhwiorvrxkmgq4xksw.png",
  "ROSE GOLD MIRROR": "https://res.cloudinary.com/varindo/image/upload/mi2bz73xqf69nxkmbnru.png",
  "ROUGE": "https://res.cloudinary.com/varindo/image/upload/euabevhsy3ev3rrl1rdc.jpg",
  "ROUGH TEAK": "https://res.cloudinary.com/varindo/image/upload/czq3lyqdcwunuxnpm5ii.jpg",
  "ROVERE ASBURGO": "https://res.cloudinary.com/varindo/image/upload/lxuw0iak795z2n989uqr.png",
  "ROVERE CARBONE": "https://res.cloudinary.com/varindo/image/upload/dg3h3vxutbyipz9sh7lq.png",
  "ROVERE RHONE": "https://res.cloudinary.com/varindo/image/upload/tmc8pafroywgtmqlodzl.png",
  "ROVERE TEXAS": "https://res.cloudinary.com/varindo/image/upload/deppcq8tysrcrawenyef.png",
  "ROVERE VERSAILLES": "https://res.cloudinary.com/varindo/image/upload/vuyappymiadw28ruo1kd.jpg",
  "ROYAL CARRARA G": "https://res.cloudinary.com/varindo/image/upload/lf7a8xsuibohgk7lbgsm.png",
  "ROYAL CARRARA MATT": "https://res.cloudinary.com/varindo/image/upload/bql6g4ubjdmtrodfgnyz.jpg",
  "RUM": "https://res.cloudinary.com/varindo/image/upload/evu303698nattmg8qgiw.jpg",
  "RUSTIC TEAK": "https://res.cloudinary.com/varindo/image/upload/iwrgx63jfjw2khivlcnj.png",
  "RYMAN ARCTIC": "https://res.cloudinary.com/varindo/image/upload/ssk1eqpinvlr2x1nhytm.jpg",
  "SAKURA PINK": "https://res.cloudinary.com/varindo/image/upload/uwljb2laybopkoy7j26y.png",
  "SALINAS OAK": "https://res.cloudinary.com/varindo/image/upload/memiq6eea5xmjpwo4o2k.png",
  "SAND BEIGE": "https://res.cloudinary.com/varindo/image/upload/aln7kam0u3qtbxpamwzs.jpg",
  "SANTHIA": "https://res.cloudinary.com/varindo/image/upload/imd5iaik8ucbnwvelopl.jpg",
  "SARTORIA": "https://res.cloudinary.com/varindo/image/upload/wh541wa5g73eiss52lr1.png",
  "SARTORIA CREMOSO": "https://res.cloudinary.com/varindo/image/upload/tfvnu51ujldnikfjsmvx.png",
  "SCARLET": "https://res.cloudinary.com/varindo/image/upload/gydbhior9en3a8zuukvg.jpg",
  "SERENE MEADOW": "https://res.cloudinary.com/varindo/image/upload/am1thuugp0rpmxro1hxt.png",
  "SERRA GRAU": "https://res.cloudinary.com/varindo/image/upload/lsds5kvs5bj4qzltygsw.jpg",
  "SILK WOOD": "https://res.cloudinary.com/varindo/image/upload/lfj7re0n3ij3infklftx.jpg",
  "SILVER BRUSH": "https://res.cloudinary.com/varindo/image/upload/ulz3wjeqirhrzmizgkrl.png",
  "SLATE GREY": "https://res.cloudinary.com/varindo/image/upload/gpovai6stiuely7rgfou.png",
  "SMART ASH": "https://res.cloudinary.com/varindo/image/upload/rq4wq3sydw7vtvwasbtt.jpg",
  "SMART ASH LIGHT": "https://res.cloudinary.com/varindo/image/upload/vankmxmhea2gv4z9n96u.png",
  "SMOG GREY": "https://res.cloudinary.com/varindo/image/upload/tmbvob5hjppt276smfd7.png",
  "SMOKE GREY 10FT": "https://res.cloudinary.com/varindo/image/upload/x7j0j4osq1np3hqov9ey.jpg",
  "SMOKE GREY 8FT": "https://res.cloudinary.com/varindo/image/upload/syw8cmlmkf2yyoowdlbh.png",
  "SMOKY STITCHED LEATHER": "https://res.cloudinary.com/varindo/image/upload/sfhepmrvabmc6hmokl43.png",
  "SMOKY TEAK": "https://res.cloudinary.com/varindo/image/upload/czaczs5wq9lywsadvkrh.png",
  "SNOW WHITE G": "https://res.cloudinary.com/varindo/image/upload/b98qhwkgbwxpws9we9uk.png",
  "SNOW WHITE V": "https://res.cloudinary.com/varindo/image/upload/qsw2f7wibvdmgjrbr9ex.jpg",
  "SOFT GREY": "https://res.cloudinary.com/varindo/image/upload/rv0sbzyjoui8u8wfbmpj.jpg",
  "SOFT PETAL": "https://res.cloudinary.com/varindo/image/upload/wmbdn1ywsz8txp0j87db.png",
  "SOFT SYLVAN WALNUT": "https://res.cloudinary.com/varindo/image/upload/ltnn38osx80ksjhf2v6d.jpg",
  "SOOTHING STORM": "https://res.cloudinary.com/varindo/image/upload/bpeomrkosheihdqjovun.png",
  "SPRING GREEN": "https://res.cloudinary.com/varindo/image/upload/mhhnodcsi9qvq3lpdwd1.png",
  "SPRING NAGARE": "https://res.cloudinary.com/varindo/image/upload/dvroxtntyqzvx9pfv7cn.png",
  "STAINLESS MATT": "https://res.cloudinary.com/varindo/image/upload/bsbwh0ieelup35hbr2ob.png",
  "STEELY GREY LINE": "https://res.cloudinary.com/varindo/image/upload/fucsfoyswjlknyr2gkph.jpg",
  "STITCH": "https://res.cloudinary.com/varindo/image/upload/ehmruyhlbp9lsoyirokq.png",
  "STITCH CLOVE": "https://res.cloudinary.com/varindo/image/upload/clamjhhvkwcdribv5hfw.jpg",
  "STITCH TINSEL": "https://res.cloudinary.com/varindo/image/upload/bnwzllt8yubhyftjd8ol.png",
  "STONE GREY": "https://res.cloudinary.com/varindo/image/upload/ucpbjgbknifrtewvhnej.jpg",
  "STORM": "https://res.cloudinary.com/varindo/image/upload/wrlf64uurwkavzigfv4k.png",
  "STRAW AREY WALNUT": "https://res.cloudinary.com/varindo/image/upload/eavtsjs9trvl2mqk5lo5.jpg",
  "STRAW ASH": "https://res.cloudinary.com/varindo/image/upload/qzbfalseoevncqqqo3yx.jpg",
  "STRAWBERRY MILK V": "https://res.cloudinary.com/varindo/image/upload/obv7ha3xrans5x890xwm.png",
  "STYLE WHITE 10FT": "https://res.cloudinary.com/varindo/image/upload/yyssgyth81vifqurw6tt.jpg",
  "STYLE WHITE 8FT": "https://res.cloudinary.com/varindo/image/upload/x9jt190ilshassptly9k.png",
  "STYLISH TEAK": "https://res.cloudinary.com/varindo/image/upload/utnlcvjsjqkbns0y4xxu.jpg",
  "SUNSILK": "https://res.cloudinary.com/varindo/image/upload/cbffamztmoi4dzglgfwf.jpg",
  "SUPERIOR WAJAR OAK": "https://res.cloudinary.com/varindo/image/upload/w0segu5fndwnrtencla6.jpg",
  "SUPREME BLACK": "https://res.cloudinary.com/varindo/image/upload/ssctepqzif8pcikdsdyz.jpg",
  "SUPREME WHITE": "https://res.cloudinary.com/varindo/image/upload/wolex8gmwpq7brgpoqst.png",
  "SYCAMORE": "https://res.cloudinary.com/varindo/image/upload/oqczfipncjkncrhujca8.png",
  "SYLVAN WALNUT": "https://res.cloudinary.com/varindo/image/upload/cim3crd5qxmktjhpk0r6.png",
  "TALISA PLUM": "https://res.cloudinary.com/varindo/image/upload/jzmt2anpsmzjwutchuqd.png",
  "TAN OAK": "https://res.cloudinary.com/varindo/image/upload/czgpaiccmrh3zqaawkxk.jpg",
  "TAURUS": "https://res.cloudinary.com/varindo/image/upload/rxeaqwyf6mw9owzjklz9.jpg",
  "TECTONA": "https://res.cloudinary.com/varindo/image/upload/vblwvqqczakzd7yiqbvs.png",
  "TERA MARBLE G": "https://res.cloudinary.com/varindo/image/upload/z6dqcyh6wrgrnplkt19a.png",
  "TERA MARBLE V": "https://res.cloudinary.com/varindo/image/upload/omarqggabamarwxvmvmx.png",
  "TERRA": "https://res.cloudinary.com/varindo/image/upload/unzalfvahcy9matuh2jy.png",
  "TERRACOTTA": "https://res.cloudinary.com/varindo/image/upload/zjqfjgdqath7ikr2ddr1.png",
  "THE FROST": "https://res.cloudinary.com/varindo/image/upload/xtwlqtu5bsaoywkjpqlr.jpg",
  "TITAN I": "https://res.cloudinary.com/varindo/image/upload/odks5i3vsxupvk5mag7e.jpg",
  "TITAN II": "https://res.cloudinary.com/varindo/image/upload/dv7vqebyuz07trh1xzwi.png",
  "TITAN III": "https://res.cloudinary.com/varindo/image/upload/wsyxl9tbcrfqqwnp15he.jpg",
  "TITAN IV": "https://res.cloudinary.com/varindo/image/upload/utbo7rqqyyc4isogbe3a.jpg",
  "TOBACCO": "https://res.cloudinary.com/varindo/image/upload/kthotoydi5irt7mnckgv.png",
  "TORINO PINE": "https://res.cloudinary.com/varindo/image/upload/ubxtmv9gumovuekdophj.png",
  "TORTORA": "https://res.cloudinary.com/varindo/image/upload/c1yres21fzvnxnphismh.jpg",
  "TRANQUIL TIDE": "https://res.cloudinary.com/varindo/image/upload/xfgrttfcg9op8y5zzipw.png",
  "TRAVERTINO": "https://res.cloudinary.com/varindo/image/upload/mczainyjrc8rr3h2d1jy.png",
  "TWILL": "https://res.cloudinary.com/varindo/image/upload/bd2kssqxlwgdn7p4cb2g.png",
  "TWILL NOTCH": "https://res.cloudinary.com/varindo/image/upload/sma9nhttrwlouccsl7eg.png",
  "TWILL TORCH": "https://res.cloudinary.com/varindo/image/upload/juiosqspkiqzhcqv4eys.jpg",
  "UNIQUE WHITE 10FT": "https://res.cloudinary.com/varindo/image/upload/ezemje1yqnxfhb5uovpo.jpg",
  "UNIQUE WHITE 8FT": "https://res.cloudinary.com/varindo/image/upload/dejlivay6um91kxxwuo9.png",
  "UNIVERSAL CHALK": "https://res.cloudinary.com/varindo/image/upload/do8ai457w6rnbz5a3ek6.png",
  "UNIVERSAL EARTH": "https://res.cloudinary.com/varindo/image/upload/mx1hbazfzqxdhqe9somr.png",
  "UNIVERSAL SAND": "https://res.cloudinary.com/varindo/image/upload/ugw6wmoopcnabd0zfobl.png",
  "URBAN ELM": "https://res.cloudinary.com/varindo/image/upload/pqxv5035ahjyewifvyqk.png",
  "URBANSTONE CHALK": "https://res.cloudinary.com/varindo/image/upload/dkf6lzizg1fqfcozvfly.png",
  "URBANSTONE CLAY": "https://res.cloudinary.com/varindo/image/upload/oz0b2fz15nabdcogyrim.png",
  "VACHETTA": "https://res.cloudinary.com/varindo/image/upload/ukoaf6rqxo03hbi95fse.png",
  "VAN DYCK BRAUN": "https://res.cloudinary.com/varindo/image/upload/jvv0w0hvzmx1o9bu3xwg.jpg",
  "VANILLA": "https://res.cloudinary.com/varindo/image/upload/l9bia0efztbeng5qkrwd.png",
  "VANILLA TEAK": "https://res.cloudinary.com/varindo/image/upload/fijiesuw9ofgov2hxmdx.jpg",
  "VENETO CRYSTAL": "https://res.cloudinary.com/varindo/image/upload/spdfs5lbxie8zujf4h3v.jpg",
  "VEYRE OAK": "https://res.cloudinary.com/varindo/image/upload/kcrcuplntqddpbf7qyqk.png",
  "VIENNA ASH": "https://res.cloudinary.com/varindo/image/upload/ps45evus1anzntgtexfx.png",
  "VINTAGE OAK": "https://res.cloudinary.com/varindo/image/upload/ec5c9b0umisxu7qs3hg0.png",
  "VIOLET CLAIR": "https://res.cloudinary.com/varindo/image/upload/badsses32w0wf7zozsrn.png",
  "VIOLET MIST": "https://res.cloudinary.com/varindo/image/upload/vsspfsydmp71tsk2lahk.png",
  "VIRGINIA BEECH": "https://res.cloudinary.com/varindo/image/upload/mdadgkudfkonu9yck5fw.png",
  "VIRGINIA WALNUT": "https://res.cloudinary.com/varindo/image/upload/dn0ujir7tx6zvyvoxqap.png",
  "VIRGO": "https://res.cloudinary.com/varindo/image/upload/dhxpcgt3thy4ete5jzo5.png",
  "VOLCANO": "https://res.cloudinary.com/varindo/image/upload/nglp5rsqtm4dyd7scnxj.jpg",
  "VOYAGE SILVER": "https://res.cloudinary.com/varindo/image/upload/onlsnzqosk1jvxdk4fjg.png",
  "WAJAR OAK": "https://res.cloudinary.com/varindo/image/upload/htf1wlhvocy4mioegroc.jpg",
  "WALD GRUN": "https://res.cloudinary.com/varindo/image/upload/psbdsnuz0h3y0wg0mlhk.jpg",
  "WARM AQUILES WALNUT": "https://res.cloudinary.com/varindo/image/upload/zp0mgds4mrmxwa3akszq.png",
  "WARM BLUSH": "https://res.cloudinary.com/varindo/image/upload/xbdmvqc8kxuw2sxaaan8.png",
  "WEISS": "https://res.cloudinary.com/varindo/image/upload/mpttxfyb49v3izpjlldq.jpg",
  "WESTERN ALDER": "https://res.cloudinary.com/varindo/image/upload/f836vii8lu8uod8nhhzp.png",
  "WHISPER GREY": "https://res.cloudinary.com/varindo/image/upload/mb520ttytfd3euepad4e.png",
  "WHISTLER COOL GRAU": "https://res.cloudinary.com/varindo/image/upload/uwcx0jgpmv1fu7zyfnev.jpg",
  "WHITE AGED PINE": "https://res.cloudinary.com/varindo/image/upload/cudy3shwtowbbbrl3amn.jpg",
  "WHITE ALDER": "https://res.cloudinary.com/varindo/image/upload/kpambwvzhhet3balsdyg.jpg",
  "WHITE ASHWOOD": "https://res.cloudinary.com/varindo/image/upload/ucltyg3lpr5z6r0bjed5.png",
  "WHITE COSMIC": "https://res.cloudinary.com/varindo/image/upload/hkmkbkjeh4pmarnjrqqe.png",
  "WHITE ELM": "https://res.cloudinary.com/varindo/image/upload/hhxgdbf8jmwbkzussx8a.jpg",
  "WHITE FLICKERS G": "https://res.cloudinary.com/varindo/image/upload/mtniblib3b3b5n3ye9qj.jpg",
  "WHITE FUNK": "https://res.cloudinary.com/varindo/image/upload/hfo1zc1afuxgqmbixj6k.jpg",
  "WHITE GALAXY": "https://res.cloudinary.com/varindo/image/upload/q0l6uyvk7uuhrl8phis5.jpg",
  "WHITE PEARL BIRDEYE": "https://res.cloudinary.com/varindo/image/upload/htm7spimdkgj7nwrgsti.png",
  "WHITE WASH OAK": "https://res.cloudinary.com/varindo/image/upload/lz4qj2tnsllwikgjcjni.jpg",
  "WOOD ART": "https://res.cloudinary.com/varindo/image/upload/cb9gbdkyd6ivxswzffom.jpg",
  "YANG MARBLE": "https://res.cloudinary.com/varindo/image/upload/uoyk2oklg3ziqykue0wf.png",
  "YELLOW CRISP": "https://res.cloudinary.com/varindo/image/upload/kbvsdooq0rsngxsubvhh.png",
  "YIN MARBLE": "https://res.cloudinary.com/varindo/image/upload/qemqlsdadfkdlanq7a8e.png",
  "ZEN WENGE": "https://res.cloudinary.com/varindo/image/upload/zvo2oxxeyhe8mjuiveot.jpg",
};

// ── EDL: edl/images — matched by product code prefix (non-p063 images) ──
// "DH 1596QT" → cloudinary URL
export const EDL_CODE_MAP: Record<string, string> = {
  "DH 1596QT": "https://res.cloudinary.com/varindo/image/upload/j2jvaynwburgosmlnhgj.png",
  "DMD 2553XM": "https://res.cloudinary.com/varindo/image/upload/jdq1umrw1ezkeaji3f8r.jpg",
  "DSL 2250STU": "https://res.cloudinary.com/varindo/image/upload/wi9wkkt9xi6evoeqmp3p.png",
  "DWT 3773W": "https://res.cloudinary.com/varindo/image/upload/lyvk3frwkjvwx78bhf5v.png",
  "DWT 3775W": "https://res.cloudinary.com/varindo/image/upload/ptobhnroszclgygxzx7y.png",
  "DWT 3776W": "https://res.cloudinary.com/varindo/image/upload/jtiran6lpcviwfzhe8th.png",
  "DWX 1063EH": "https://res.cloudinary.com/varindo/image/upload/sv3zwtzx2geuwf31lksy.png",
  "DYM 2709PG": "https://res.cloudinary.com/varindo/image/upload/dukebys4752hyj6kelfy.png",
  "EMM 2740": "https://res.cloudinary.com/varindo/image/upload/spztbqln0ghoaegukrtj.png",
  "ESF 5250T": "https://res.cloudinary.com/varindo/image/upload/vh8nfrfsgrsvwllp7drn.png",
  "ESF 5730T": "https://res.cloudinary.com/varindo/image/upload/ax7nliaa5higtynmabpc.png",
  "ESF 5890T": "https://res.cloudinary.com/varindo/image/upload/fgxzlvoscenr69c7bcoj.png",
  "ESG 5150N": "https://res.cloudinary.com/varindo/image/upload/exxyu0gm1kvnyw5rmv1a.png",
  "EWP 3242M": "https://res.cloudinary.com/varindo/image/upload/wfftztpfivcibaudna3c.png",
};
// ── EDL: edl/images/edl_add/{random_id}.{ext} ─────────────────────────────
// Numeric ID extracted from product code (e.g. "DA 7180C" → 7180)
// num (stripped of leading zeros) → full URL
export const EDL_ADD_NUM_MAP: Record<string, string> = {
  "1": "https://res.cloudinary.com/varindo/image/upload/spgkgz5rh3mn3tl6ml6s.jpg",
  "2": "https://res.cloudinary.com/varindo/image/upload/agv3t7nycu9x2vlwsyjr.png",
  "5": "https://res.cloudinary.com/varindo/image/upload/f776nyvmuqzm7heu8l3r.jpg",
  "8": "https://res.cloudinary.com/varindo/image/upload/l7hagbyhtf1qttjfgshy.jpg",
  "11": "https://res.cloudinary.com/varindo/image/upload/wexsnvgtm0tpo6v8ztwa.png",
  "22": "https://res.cloudinary.com/varindo/image/upload/vidshqcdaeacuwrmjcbd.jpg",
  "25": "https://res.cloudinary.com/varindo/image/upload/wicuygw1o1atrb2zi1bu.jpg",
  "55": "https://res.cloudinary.com/varindo/image/upload/uevvc6xwem7wclgonwla.jpg",
  "75": "https://res.cloudinary.com/varindo/image/upload/ptchypxexcaoomv1kbjp.jpg",
  "77": "https://res.cloudinary.com/varindo/image/upload/ypwsqn7tvtznuyqh09j3.jpg",
  "80": "https://res.cloudinary.com/varindo/image/upload/b5xmqw3wdojvx9th704w.jpg",
  "85": "https://res.cloudinary.com/varindo/image/upload/smyqxfw2rublz0gmz2fa.jpg",
  "88": "https://res.cloudinary.com/varindo/image/upload/showidz2t70lvpbdnql6.jpg",
  "206": "https://res.cloudinary.com/varindo/image/upload/ywedarzrgaibuhbqpbx7.jpg",
  "289": "https://res.cloudinary.com/varindo/image/upload/yl33y7pdz8gb1molhcpu.jpg",
  "301": "https://res.cloudinary.com/varindo/image/upload/flyniphq9wjhqr9vg4ea.jpg",
  "320": "https://res.cloudinary.com/varindo/image/upload/m95qaclmlogxxsbsmt5o.jpg",
  "370": "https://res.cloudinary.com/varindo/image/upload/pcpl8si7s3pry2dmvdvs.jpg",
  "400": "https://res.cloudinary.com/varindo/image/upload/eublsuycwmljcsqsnglu.png",
  "606": "https://res.cloudinary.com/varindo/image/upload/iq2bydzbghplvria3krq.jpg",
  "648": "https://res.cloudinary.com/varindo/image/upload/yedpglbuhmcn9ayfe6ps.jpg",
  "702": "https://res.cloudinary.com/varindo/image/upload/ouhygbhqpazgsvek15ww.jpg",
  "1054": "https://res.cloudinary.com/varindo/image/upload/gnoqt6uls4nt8gxzsvzw.jpg",
  "1061": "https://res.cloudinary.com/varindo/image/upload/eazpo4vakoxz0hcaohip.jpg",
  "1311": "https://res.cloudinary.com/varindo/image/upload/qawmbgrka3ypnqnjtgjs.png",
  "1380": "https://res.cloudinary.com/varindo/image/upload/f77yyh6grjb61fuwz34n.jpg",
  "1557": "https://res.cloudinary.com/varindo/image/upload/ol4x5tz29yxarrr9mez6.jpg",
  "1558": "https://res.cloudinary.com/varindo/image/upload/enahp2bi8dlnkhoc3vkz.jpg",
  "1576": "https://res.cloudinary.com/varindo/image/upload/hmymfxvq7ru63vrjce5d.jpg",
  "1584": "https://res.cloudinary.com/varindo/image/upload/onldwiyfanu72tgp6ivz.jpg",
  "1586": "https://res.cloudinary.com/varindo/image/upload/nr0zz0cml34psinuug01.jpg",
  "1587": "https://res.cloudinary.com/varindo/image/upload/lsn0pad8ho3qncq7knx3.jpg",
  "1588": "https://res.cloudinary.com/varindo/image/upload/uvbzbq8tlfirdkwen73h.jpg",
  "1597": "https://res.cloudinary.com/varindo/image/upload/eqatfakap2xuyo7vmfhm.png",
  "1741": "https://res.cloudinary.com/varindo/image/upload/oc01bydavt8o5uoplbjb.png",
  "1761": "https://res.cloudinary.com/varindo/image/upload/vrbh1r4lmbw80mfdz5zs.jpg",
  "1762": "https://res.cloudinary.com/varindo/image/upload/a9mhzjzlm2lrm1xlsdmh.png",
  "1787": "https://res.cloudinary.com/varindo/image/upload/tqazwojvqqomdcy6oqbi.jpg",
  "2048": "https://res.cloudinary.com/varindo/image/upload/z0kxbelenhacbhkq9nav.png",
  "2121": "https://res.cloudinary.com/varindo/image/upload/by2v5eqngnfalvzkn6i3.jpg",
  "2122": "https://res.cloudinary.com/varindo/image/upload/xmxvt6aeqywejeqly5hi.png",
  "2231": "https://res.cloudinary.com/varindo/image/upload/hlftsfwkdtpepoke54rw.jpg",
  "2235": "https://res.cloudinary.com/varindo/image/upload/imb4its00opsrfdondn9.jpg",
  "2274": "https://res.cloudinary.com/varindo/image/upload/m9kpck2o6lcumfyaq4ri.jpg",
  "2276": "https://res.cloudinary.com/varindo/image/upload/bxktc4tx6s8rm5cwywlf.jpg",
  "2300": "https://res.cloudinary.com/varindo/image/upload/f6u2lhmpelnji5ufmdpl.jpg",
  "2320": "https://res.cloudinary.com/varindo/image/upload/vbjjqoyskft3y4m5labl.jpg",
  "2358": "https://res.cloudinary.com/varindo/image/upload/cbucjcs3wurrb9ln5pva.png",
  "2380": "https://res.cloudinary.com/varindo/image/upload/k6duu5je62fvypy0a3wl.png",
  "2390": "https://res.cloudinary.com/varindo/image/upload/u9mb4ryohb5bux4nhnot.jpg",
  "2396": "https://res.cloudinary.com/varindo/image/upload/jxexnmr7muyllj0wurwa.jpg",
  "2552": "https://res.cloudinary.com/varindo/image/upload/dt7eerxicbyoydmkkqzv.jpg",
  "2557": "https://res.cloudinary.com/varindo/image/upload/l1padx0gxuhjxjarreth.jpg",
  "2558": "https://res.cloudinary.com/varindo/image/upload/hxfwimrwig7btjbofdlr.jpg",
  "2576": "https://res.cloudinary.com/varindo/image/upload/ntaz9ian2zqbid29i952.jpg",
  "2584": "https://res.cloudinary.com/varindo/image/upload/xvnd6qhsza8tnxshxi4e.png",
  "2586": "https://res.cloudinary.com/varindo/image/upload/yjpaqgervtxmm7dbtdux.jpg",
  "2587": "https://res.cloudinary.com/varindo/image/upload/c2q04aap4vkv2oxm0b86.jpg",
  "2588": "https://res.cloudinary.com/varindo/image/upload/babaf32wzv3czw1ob2ln.jpg",
  "2692": "https://res.cloudinary.com/varindo/image/upload/u79sfrbmd3wenu9taxut.jpg",
  "2739": "https://res.cloudinary.com/varindo/image/upload/g5nznddi8svm1g4n191x.jpg",
  "2766": "https://res.cloudinary.com/varindo/image/upload/ob1dtehogtonadvyuigd.jpg",
  "2806": "https://res.cloudinary.com/varindo/image/upload/x8ime1huglvbt4cfehl6.jpg",
  "2818": "https://res.cloudinary.com/varindo/image/upload/hmwxdbnbgepbkng7wqcw.jpg",
  "3012": "https://res.cloudinary.com/varindo/image/upload/co2hhgdtczylebdn4esv.jpg",
  "3048": "https://res.cloudinary.com/varindo/image/upload/nh7juctvsqjtb626pm3u.jpg",
  "3050": "https://res.cloudinary.com/varindo/image/upload/hyfnvkyv5htbtlpltd7d.png",
  "3117": "https://res.cloudinary.com/varindo/image/upload/h2cfhd5v4jwjr3zwaa7b.jpg",
  "3131": "https://res.cloudinary.com/varindo/image/upload/gjt6lzxrlhx5wlsmu7ue.png",
  "3132": "https://res.cloudinary.com/varindo/image/upload/himzchvf71u5qaxk7t2k.jpg",
  "3133": "https://res.cloudinary.com/varindo/image/upload/vn6n7zepqtfmaotjaigp.jpg",
  "3155": "https://res.cloudinary.com/varindo/image/upload/lokgxolk4ax8rfhuzuzc.jpg",
  "3165": "https://res.cloudinary.com/varindo/image/upload/cpwzpfltaidu4hmgyc4u.jpg",
  "3225": "https://res.cloudinary.com/varindo/image/upload/umcgteggavaeb7vdwdld.jpg",
  "3226": "https://res.cloudinary.com/varindo/image/upload/i9i5y7cvonbm9ecchsq3.jpg",
  "3286": "https://res.cloudinary.com/varindo/image/upload/lcthhdlfpr20dq12z90d.png",
  "3294": "https://res.cloudinary.com/varindo/image/upload/ui4dnoypy5hgxz2uwiaf.jpg",
  "3295": "https://res.cloudinary.com/varindo/image/upload/numzvulub9wfjshrorzh.png",
  "3342": "https://res.cloudinary.com/varindo/image/upload/u3oywzzdymrpr0rrxwr1.jpg",
  "3346": "https://res.cloudinary.com/varindo/image/upload/vdr4y9pwwi1tucamwo3r.jpg",
  "3411": "https://res.cloudinary.com/varindo/image/upload/vmr51iuujxp6limoo2hv.jpg",
  "3412": "https://res.cloudinary.com/varindo/image/upload/pzbbz2010u86xa86khvh.jpg",
  "3451": "https://res.cloudinary.com/varindo/image/upload/ktd1zos0voqcudcabvef.jpg",
  "3452": "https://res.cloudinary.com/varindo/image/upload/dpq0besrrjacivonxath.jpg",
  "3712": "https://res.cloudinary.com/varindo/image/upload/xin2sdkcan1e12gp20m1.jpg",
  "3902": "https://res.cloudinary.com/varindo/image/upload/sjl31h35ymexy3zph6u4.png",
  "3904": "https://res.cloudinary.com/varindo/image/upload/ot0hi4vywe3bkrnrsmec.jpg",
  "4401": "https://res.cloudinary.com/varindo/image/upload/u2w2mm2mia3zr9taocjy.png",
  "4402": "https://res.cloudinary.com/varindo/image/upload/hgjxynvz02lnpchomblx.jpg",
  "4412": "https://res.cloudinary.com/varindo/image/upload/joueyrc31yavzo9luuca.jpg",
  "4445": "https://res.cloudinary.com/varindo/image/upload/fseot1sz3x63o3yt7yvt.jpg",
  "4451": "https://res.cloudinary.com/varindo/image/upload/nlp6riliexsqbpyoupqi.png",
  "4518": "https://res.cloudinary.com/varindo/image/upload/lf8fu1mvywc4fj6kouex.jpg",
  "4533": "https://res.cloudinary.com/varindo/image/upload/rtldbtflxvg15ktzhqgr.jpg",
  "4545": "https://res.cloudinary.com/varindo/image/upload/w8fvae81he8xm3av9ig4.jpg",
  "4585": "https://res.cloudinary.com/varindo/image/upload/bdkcbxouysant9b6hyah.jpg",
  "4587": "https://res.cloudinary.com/varindo/image/upload/padlv6vkycyzwdebgn09.png",
  "4605": "https://res.cloudinary.com/varindo/image/upload/k11ipnm3tsuoycgxpi1g.jpg",
  "4613": "https://res.cloudinary.com/varindo/image/upload/ph5m4epmeub0msjsfqm3.jpg",
  "4616": "https://res.cloudinary.com/varindo/image/upload/f9037chll1kxgicneo6c.jpg",
  "4682": "https://res.cloudinary.com/varindo/image/upload/hmvmferjx6o8caknr2l6.jpg",
  "4749": "https://res.cloudinary.com/varindo/image/upload/ekqpvssi4gdvfzhm5z6b.jpg",
  "4778": "https://res.cloudinary.com/varindo/image/upload/xlxfvdyrocrdoy2waabh.jpg",
  "5001": "https://res.cloudinary.com/varindo/image/upload/pn6ep3olxeuhgmeb7eml.jpg",
  "5002": "https://res.cloudinary.com/varindo/image/upload/ecuootpijjebhs5imogs.jpg",
  "5020": "https://res.cloudinary.com/varindo/image/upload/vclff5zx4egytjfohvcx.jpg",
  "5022": "https://res.cloudinary.com/varindo/image/upload/uqfmnfst2uilg2ng237y.jpg",
  "5040": "https://res.cloudinary.com/varindo/image/upload/esncgd5jqquqwy3y6cvm.jpg",
  "5130": "https://res.cloudinary.com/varindo/image/upload/zfuuhbirxaxsmoacchec.jpg",
  "5140": "https://res.cloudinary.com/varindo/image/upload/cgsptx7zdbyczlahlrc4.jpg",
  "5160": "https://res.cloudinary.com/varindo/image/upload/wondfykr1gd0pgdwybdn.jpg",
  "5212": "https://res.cloudinary.com/varindo/image/upload/xdamjwcjmloeornsomkw.jpg",
  "5414": "https://res.cloudinary.com/varindo/image/upload/ft9onymj5gopiw8bclzj.png",
  "5709": "https://res.cloudinary.com/varindo/image/upload/bkvt5ij9uxnusd2zgpvf.jpg",
  "5724": "https://res.cloudinary.com/varindo/image/upload/st0k4pvh6qw2uumgawqr.png",
  "5725": "https://res.cloudinary.com/varindo/image/upload/y0upj3uescobmqjb8co5.jpg",
  "5738": "https://res.cloudinary.com/varindo/image/upload/ftiblix1li6lpt5spuj5.png",
  "6000": "https://res.cloudinary.com/varindo/image/upload/eumzurm7ila2iweruxpt.jpg",
  "6080": "https://res.cloudinary.com/varindo/image/upload/pqbi04rvkdx0m1agvkyq.jpg",
  "6084": "https://res.cloudinary.com/varindo/image/upload/tvc4h4yxhnpvwnmnwvxz.jpg",
  "6210": "https://res.cloudinary.com/varindo/image/upload/iggp6atb6vlzkz5xtm74.jpg",
  "6307": "https://res.cloudinary.com/varindo/image/upload/nwz5z07coayxaiww7vz0.jpg",
  "6350": "https://res.cloudinary.com/varindo/image/upload/osojfew6yt6lbodgqnax.jpg",
  "6460": "https://res.cloudinary.com/varindo/image/upload/ucyjqlcswtknkzxhqps4.jpg",
  "6865": "https://res.cloudinary.com/varindo/image/upload/h73edfjslcpa3nyeszr1.jpg",
  "6866": "https://res.cloudinary.com/varindo/image/upload/klkbwj3wbtuo4fr3umww.jpg",
  "6889": "https://res.cloudinary.com/varindo/image/upload/afws5ojin7ypuy7ppt0z.png",
  "6951": "https://res.cloudinary.com/varindo/image/upload/jjvdvncemuty5qifkhdk.jpg",
  "6953": "https://res.cloudinary.com/varindo/image/upload/xul6wwtwhab9brtls400.jpg",
  "7004": "https://res.cloudinary.com/varindo/image/upload/katxvwxxsubkqnibx9tc.png",
  "7119": "https://res.cloudinary.com/varindo/image/upload/azyfqen67yr4nwma2udv.jpg",
  "7180": "https://res.cloudinary.com/varindo/image/upload/rszm5hkrzte623na5co2.jpg",
  "7448": "https://res.cloudinary.com/varindo/image/upload/lmyblk7tfqpo6s9heb6f.jpg",
  "7772": "https://res.cloudinary.com/varindo/image/upload/fzgn5xip0ghgicaf4plx.png",
  "8000": "https://res.cloudinary.com/varindo/image/upload/ulcmycccxz9u2i7op22z.png",
  "8097": "https://res.cloudinary.com/varindo/image/upload/oalrqioxpbnhheqbh5se.jpg",
  "8111": "https://res.cloudinary.com/varindo/image/upload/kmbifn2pgn5blmqe7fck.jpg",
  "8195": "https://res.cloudinary.com/varindo/image/upload/qiapu3vjqxpl8by8n1j9.jpg",
  "8197": "https://res.cloudinary.com/varindo/image/upload/gcgu5cykpxpsozrhlpuq.png",
  "8211": "https://res.cloudinary.com/varindo/image/upload/smpcrrvdzdxjsose9ery.jpg",
  "8300": "https://res.cloudinary.com/varindo/image/upload/o23mri1ej0kvm8ix84fk.png",
  "8320": "https://res.cloudinary.com/varindo/image/upload/lvnogmynbhv4afopkbnx.jpg",
  "8390": "https://res.cloudinary.com/varindo/image/upload/dciaa7fd0lh8bl9rqryb.jpg",
  "8395": "https://res.cloudinary.com/varindo/image/upload/jjtg6ydcnzk8xudkum7e.jpg",
  "8396": "https://res.cloudinary.com/varindo/image/upload/hzklevyfzkwzwvmnx1we.jpg",
  "9029": "https://res.cloudinary.com/varindo/image/upload/ws1ar6mnhn5wpeme1por.jpg",
  "9070": "https://res.cloudinary.com/varindo/image/upload/sfx0g0ejbady2co76alk.jpg",
  "9090": "https://res.cloudinary.com/varindo/image/upload/myyns077naqzpytxuuba.jpg",
  "9139": "https://res.cloudinary.com/varindo/image/upload/rnyswith24hsgtzu3kzg.png",
  "9275": "https://res.cloudinary.com/varindo/image/upload/af6rgdncxyquo6t1o4x1.jpg",
  "9380": "https://res.cloudinary.com/varindo/image/upload/urnjlyboz2mikkvhmezg.png",
  "9389": "https://res.cloudinary.com/varindo/image/upload/g8ymagso4ap0hxpcbqfe.jpg",
  "9826": "https://res.cloudinary.com/varindo/image/upload/cvg8vpznso0oy99hbnih.jpg",
};